/**
 * casterAuth.ts — Auth helpers for the caster system.
 *
 * - bcryptjs verifies user passwords against hashes stored in auth.caster_users
 *   (those hashes were generated by Postgres' crypt() with gen_salt('bf', 12),
 *   which is byte-compatible with bcryptjs).
 * - jose signs/verifies JWT cookies (HS256). The secret comes from JWT_SECRET.
 * - Cookie config: httpOnly, secure, sameSite=lax, 7 days max-age.
 */

import bcrypt from 'bcryptjs';
import { SignJWT, jwtVerify } from 'jose';
import { adminPool } from './casterDb';

type CookieOptions = {
  name: string;
  value: string;
  httpOnly: boolean;
  secure: boolean;
  sameSite: 'lax' | 'strict' | 'none';
  path: string;
  maxAge: number;
};

export const CASTER_COOKIE_NAME = 'ls_caster';
const COOKIE_MAX_AGE_SEC = 60 * 60 * 24 * 7; // 7 días

export interface CasterIdentity {
  id: number;
  username: string;
  display_name: string | null;
}

function getJwtSecret(): Uint8Array {
  const s = process.env.JWT_SECRET;
  if (!s || s.length < 32) {
    throw new Error('JWT_SECRET missing or too short (min 32 chars)');
  }
  return new TextEncoder().encode(s);
}

/* ════════════════════════════════════════════════════════════════════════════
   Password verification
   ════════════════════════════════════════════════════════════════════════════ */

/**
 * Verifica las credenciales contra auth.caster_users.
 * Devuelve la identidad si match, o null si no existe / password incorrecta.
 *
 * Nota: aunque el usuario no exista, hacemos un bcrypt.compare contra un hash
 * dummy para que el tiempo de respuesta sea constante (anti timing-attack).
 */
const DUMMY_HASH = '$2a$12$DUMMYDUMMYDUMMYDUMMYDuU.LL5oxV6Ut6oMc4u3qxw5iTM7VlPG';

export async function verifyCasterCredentials(
  username: string,
  password: string,
): Promise<CasterIdentity | null> {
  // Username sólo puede contener [a-z0-9_]; rechazo cualquier otra cosa antes
  // de tocar la BD, por defensa.
  if (!/^[a-z0-9_]{1,50}$/.test(username)) return null;

  const { rows } = await adminPool.query<{
    id: number;
    username: string;
    display_name: string | null;
    password_hash: string;
    active: boolean;
  }>(
    `SELECT id, username, display_name, password_hash, active
     FROM auth.caster_users
     WHERE username = $1`,
    [username],
  );

  const user = rows[0];
  const hashToCheck = user?.password_hash ?? DUMMY_HASH;
  const ok = await bcrypt.compare(password, hashToCheck);

  if (!ok || !user || !user.active) return null;

  // last_login (best-effort, no bloqueante)
  adminPool
    .query('UPDATE auth.caster_users SET last_login = NOW() WHERE id = $1', [user.id])
    .catch(() => undefined);

  return { id: user.id, username: user.username, display_name: user.display_name };
}

/* ════════════════════════════════════════════════════════════════════════════
   JWT (firma/verificación)
   ════════════════════════════════════════════════════════════════════════════ */

export async function signCasterJwt(identity: CasterIdentity): Promise<string> {
  return await new SignJWT({
    sub: String(identity.id),
    username: identity.username,
    display_name: identity.display_name ?? '',
  })
    .setProtectedHeader({ alg: 'HS256' })
    .setIssuedAt()
    .setExpirationTime('7d')
    .sign(getJwtSecret());
}

export async function verifyCasterJwt(token: string | undefined): Promise<CasterIdentity | null> {
  if (!token) return null;
  try {
    const { payload } = await jwtVerify(token, getJwtSecret());
    if (!payload.sub) return null;
    return {
      id: Number(payload.sub),
      username: String(payload.username || ''),
      display_name: (payload.display_name as string) || null,
    };
  } catch {
    return null;
  }
}

/* ════════════════════════════════════════════════════════════════════════════
   Cookie helpers
   ════════════════════════════════════════════════════════════════════════════ */

export function buildCasterCookie(token: string): CookieOptions {
  return {
    name: CASTER_COOKIE_NAME,
    value: token,
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'lax',
    path: '/',
    maxAge: COOKIE_MAX_AGE_SEC,
  };
}

export function buildClearCasterCookie(): CookieOptions {
  return {
    name: CASTER_COOKIE_NAME,
    value: '',
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'lax',
    path: '/',
    maxAge: 0,
  };
}
