-- ============================================================================
-- champion_archetypes — Maps each champion to 1-2 gameplay archetypes.
-- Used by the player evaluation algorithm to weight metrics per champion.
-- ============================================================================

CREATE TABLE IF NOT EXISTS champion_archetypes (
  champion_name        TEXT PRIMARY KEY,
  primary_archetype    TEXT NOT NULL,
  secondary_archetype  TEXT            -- nullable, some champions are single-archetype
);

-- Truncate to allow re-running safely
TRUNCATE champion_archetypes;

INSERT INTO champion_archetypes (champion_name, primary_archetype, secondary_archetype) VALUES
('Aatrox',          'Luchador',     NULL),
('Ahri',            'Mago',         'Asesino'),
('Akali',           'Asesino',      NULL),
('Akshan',          'Tirador',      'Asesino'),
('Alistar',         'Tanque',       'Resistencia'),
('Ambessa',         'Luchador',     'Asesino'),
('Amumu',           'Tanque',       'Resistencia'),
('Anivia',          'Mago',         NULL),
('Annie',           'Mago',         'Resistencia'),
('Aphelios',        'Tirador',      NULL),
('Ashe',            'Tirador',      'Asistencia'),
('Aurelion Sol',    'Mago',         NULL),
('Aurora',          'Mago',         'Asesino'),
('Azir',            'Mago',         'Tirador'),
('Bardo',           'Asistencia',   'Mago'),
('Bel''Veth',       'Luchador',     NULL),
('Blitzcrank',      'Tanque',       'Resistencia'),
('Brand',           'Mago',         'Resistencia'),
('Braum',           'Tanque',       'Resistencia'),
('Briar',           'Luchador',     'Asesino'),
('Caitlyn',         'Tirador',      NULL),
('Camille',         'Luchador',     'Asesino'),
('Cassiopeia',      'Mago',         NULL),
('Cho''Gath',       'Tanque',       'Mago'),
('Corki',           'Tirador',      'Mago'),
('Darius',          'Luchador',     'Tanque'),
('Diana',           'Luchador',     'Asesino'),
('Dr. Mundo',       'Tanque',       'Luchador'),
('Draven',          'Tirador',      NULL),
('Ekko',            'Asesino',      'Mago'),
('Elise',           'Asesino',      'Mago'),
('Evelynn',         'Asesino',      'Mago'),
('Ezreal',          'Tirador',      'Mago'),
('Fiddlesticks',    'Mago',         'Resistencia'),
('Fiora',           'Luchador',     'Asesino'),
('Fizz',            'Asesino',      'Luchador'),
('Galio',           'Tanque',       'Mago'),
('Gangplank',       'Luchador',     NULL),
('Garen',           'Luchador',     'Tanque'),
('Gnar',            'Luchador',     'Tanque'),
('Gragas',          'Luchador',     'Mago'),
('Graves',          'Tirador',      NULL),
('Gwen',            'Luchador',     NULL),
('Hecarim',         'Luchador',     'Tanque'),
('Heimerdinger',    'Mago',         'Asistencia'),
('Hwei',            'Mago',         'Asistencia'),
('Illaoi',          'Luchador',     'Tanque'),
('Irelia',          'Luchador',     'Asesino'),
('Ivern',           'Asistencia',   'Mago'),
('Janna',           'Asistencia',   'Mago'),
('Jarvan IV',       'Luchador',     'Tanque'),
('Jax',             'Luchador',     NULL),
('Jayce',           'Luchador',     'Tirador'),
('Jhin',            'Tirador',      'Mago'),
('Jinx',            'Tirador',      NULL),
('K''Sante',        'Tanque',       'Luchador'),
('Kai''Sa',         'Tirador',      'Mago'),
('Kalista',         'Tirador',      NULL),
('Karma',           'Mago',         'Asistencia'),
('Karthus',         'Mago',         NULL),
('Kassadin',        'Asesino',      'Mago'),
('Katarina',        'Asesino',      'Mago'),
('Kayle',           'Mago',         'Tirador'),
('Kayn',            'Luchador',     'Asesino'),
('Kennen',          'Mago',         NULL),
('Kha''Zix',        'Asesino',      NULL),
('Kindred',         'Tirador',      NULL),
('Kled',            'Luchador',     NULL),
('Kog''Maw',        'Tirador',      'Mago'),
('LeBlanc',         'Asesino',      'Mago'),
('Lee Sin',         'Luchador',     'Asesino'),
('Leona',           'Tanque',       'Resistencia'),
('Lillia',          'Luchador',     'Mago'),
('Lissandra',       'Mago',         NULL),
('Lucian',          'Tirador',      'Asesino'),
('Lulu',            'Asistencia',   'Mago'),
('Lux',             'Mago',         'Asistencia'),
('Maestro Yi',      'Luchador',     'Asesino'),
('Malphite',        'Tanque',       'Mago'),
('Malzahar',        'Mago',         NULL),
('Maokai',          'Tanque',       'Asistencia'),
('Mel',             'Mago',         'Asistencia'),
('Milio',           'Asistencia',   'Mago'),
('Miss Fortune',    'Tirador',      'Mago'),
('Mordekaiser',     'Luchador',     'Mago'),
('Morgana',         'Asistencia',   'Mago'),
('Naafiri',         'Asesino',      'Luchador'),
('Nami',            'Asistencia',   'Mago'),
('Nasus',           'Luchador',     'Tanque'),
('Nautilus',        'Tanque',       'Asistencia'),
('Neeko',           'Mago',         'Asistencia'),
('Nidalee',         'Asesino',      'Mago'),
('Nilah',           'Luchador',     'Asesino'),
('Nocturne',        'Luchador',     'Asesino'),
('Nunu y Willump',  'Tanque',       'Mago'),
('Olaf',            'Luchador',     'Tanque'),
('Orianna',         'Mago',         'Asistencia'),
('Ornn',            'Tanque',       NULL),
('Pantheon',        'Luchador',     'Asesino'),
('Poppy',           'Tanque',       'Luchador'),
('Pyke',            'Asistencia',   'Asesino'),
('Qiyana',          'Asesino',      NULL),
('Quinn',           'Tirador',      'Asesino'),
('Rakan',           'Asistencia',   NULL),
('Rammus',          'Tanque',       NULL),
('Rek''Sai',        'Luchador',     'Tanque'),
('Rell',            'Tanque',       'Asistencia'),
('Renata Glasc',    'Asistencia',   'Mago'),
('Renekton',        'Luchador',     'Tanque'),
('Rengar',          'Asesino',      'Luchador'),
('Riven',           'Luchador',     'Asesino'),
('Rumble',          'Luchador',     'Mago'),
('Ryze',            'Mago',         NULL),
('Samira',          'Tirador',      'Asesino'),
('Sejuani',         'Tanque',       NULL),
('Senna',           'Asistencia',   'Tirador'),
('Seraphine',       'Asistencia',   'Mago'),
('Sett',            'Luchador',     'Tanque'),
('Shaco',           'Asesino',      NULL),
('Shen',            'Tanque',       NULL),
('Shyvana',         'Luchador',     'Asesino'),
('Singed',          'Tanque',       'Mago'),
('Sion',            'Tanque',       'Luchador'),
('Sivir',           'Tirador',      NULL),
('Skarner',         'Tanque',       'Luchador'),
('Smolder',         'Tirador',      'Mago'),
('Sona',            'Asistencia',   'Mago'),
('Soraka',          'Asistencia',   'Mago'),
('Swain',           'Mago',         'Asistencia'),
('Sylas',           'Mago',         'Asesino'),
('Syndra',          'Mago',         NULL),
('Tahm Kench',      'Tanque',       'Asistencia'),
('Taliyah',         'Mago',         'Asistencia'),
('Talon',           'Asesino',      NULL),
('Taric',           'Asistencia',   'Tanque'),
('Teemo',           'Tirador',      'Mago'),
('Thresh',          'Asistencia',   'Tanque'),
('Tristana',        'Tirador',      'Asesino'),
('Trundle',         'Luchador',     'Tanque'),
('Tryndamere',      'Luchador',     'Asesino'),
('Twisted Fate',    'Mago',         'Tirador'),
('Twitch',          'Tirador',      'Asesino'),
('Udyr',            'Luchador',     'Tanque'),
('Urgot',           'Luchador',     'Tanque'),
('Varus',           'Tirador',      'Mago'),
('Vayne',           'Tirador',      'Asesino'),
('Veigar',          'Mago',         NULL),
('Vel''Koz',        'Mago',         'Asistencia'),
('Vex',             'Mago',         NULL),
('Vi',              'Luchador',     'Asesino'),
('Viego',           'Luchador',     'Asesino'),
('Viktor',          'Mago',         NULL),
('Vladimir',        'Mago',         'Luchador'),
('Volibear',        'Luchador',     'Tanque'),
('Warwick',         'Luchador',     'Tanque'),
('Wukong',          'Luchador',     'Tanque'),
('Xayah',           'Tirador',      NULL),
('Xerath',          'Mago',         'Asistencia'),
('Xin Zhao',        'Luchador',     'Tanque'),
('Yasuo',           'Luchador',     'Asesino'),
('Yone',            'Luchador',     'Asesino'),
('Yorick',          'Luchador',     'Tanque'),
('Yunara',          'Tirador',      NULL),
('Yuumi',           'Asistencia',   'Mago'),
('Zaahen',          'Luchador',     'Asesino'),
('Zac',             'Tanque',       'Luchador'),
('Zed',             'Asesino',      NULL),
('Zeri',            'Tirador',      NULL),
('Ziggs',           'Mago',         NULL),
('Zilean',          'Asistencia',   'Mago'),
('Zoe',             'Mago',         NULL),
('Zyra',            'Mago',         'Asistencia');

-- Index for fast lookups by archetype
CREATE INDEX IF NOT EXISTS idx_archetypes_primary ON champion_archetypes (primary_archetype);
CREATE INDEX IF NOT EXISTS idx_archetypes_secondary ON champion_archetypes (secondary_archetype);
