-- ═══════════════════════════════════════════════════════════════════════════════
-- digest_runs — Snapshot of each 8h digest window (used for sparklines and
--               historical comparisons in the daily-digest email).
--
-- One row per Lambda invocation of daily-digest (3 x día en Europe/Madrid).
-- Agrega los totales por ventana y por liga en un JSON compacto para que el
-- sparkline de 7 días se renderice con una sola query (WHERE started_at > NOW - 7d).
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS digest_runs (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Ventana [window_start_utc, window_end_utc) que cubrió el correo
  window_start_utc   TIMESTAMPTZ NOT NULL,
  window_end_utc     TIMESTAMPTZ NOT NULL,
  -- Momento real de envío (puede no coincidir con el borde de la ventana si hay lag)
  started_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at        TIMESTAMPTZ,
  -- Slot semántico: '00', '08', '16' en hora Madrid — facilita queries por hora del día
  slot_madrid        TEXT NOT NULL CHECK (slot_madrid IN ('00', '08', '16')),
  -- Totales agregados para la ventana
  matches_total      INTEGER NOT NULL DEFAULT 0,
  matches_completo   INTEGER NOT NULL DEFAULT 0,
  matches_parcial    INTEGER NOT NULL DEFAULT 0,
  matches_solo_res   INTEGER NOT NULL DEFAULT 0,
  matches_programado INTEGER NOT NULL DEFAULT 0,
  matches_fallo      INTEGER NOT NULL DEFAULT 0,
  matches_walkover   INTEGER NOT NULL DEFAULT 0,
  -- Conteos auxiliares
  games_total        INTEGER NOT NULL DEFAULT 0,
  games_with_frames  INTEGER NOT NULL DEFAULT 0,
  leagues_active     INTEGER NOT NULL DEFAULT 0,
  -- Parche activo predominante en la ventana (para el header)
  patch_active       TEXT,
  -- Breakdown por liga en JSON: { "LCK": { "completo": 4, "parcial": 0, ... }, ... }
  -- Se usa para render de sparklines: basta leer 21 filas (7d * 3 slots) y pivotar.
  per_league         JSONB NOT NULL DEFAULT '{}'::jsonb,
  -- Mensaje de SES para poder cruzar con bounces/complaints si hace falta
  ses_message_id     TEXT,
  -- Status del run propio (por si el handler captura error parcial)
  status             TEXT NOT NULL DEFAULT 'ok' CHECK (status IN ('ok', 'partial', 'error'))
);

-- Query principal del sparkline: "dame los últimos 21 runs"
CREATE INDEX IF NOT EXISTS idx_digest_runs_started
  ON digest_runs (started_at DESC);

-- Query del offseason tracker: "¿cuándo fue el último run con actividad en liga X?"
CREATE INDEX IF NOT EXISTS idx_digest_runs_window
  ON digest_runs (window_start_utc);

-- ═══════════════════════════════════════════════════════════════════════════════
-- ingestion_failures — Errores estructurados del pipeline (auto-ingest,
--                      match-poller, fetch-to-postgres).
--
-- Sustituye a scrape-the-logs con CloudWatch Logs Insights. Cada fallo captura
-- contexto suficiente para aparecer en el correo del próximo slot sin queries
-- externas: match_id + liga + fase + mensaje + stacktrace corto.
-- ═══════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS ingestion_failures (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- Fuente del fallo
  source         TEXT NOT NULL CHECK (source IN ('auto-ingest', 'match-poller', 'fetch-to-postgres', 'other')),
  -- Contexto del fallo (todos opcionales para que cualquier punto de fallo pueda escribir algo)
  league_slug    TEXT,
  league_id      INTEGER,
  match_id       INTEGER,
  stage          TEXT,               -- 'fetch_matches', 'fetch_games', 'insert_match', 'insert_game_players', 'insert_game_frames', 'cloudwatch_metric', ...
  error_type     TEXT,               -- 'http_429', 'http_500', 'timeout', 'pg_constraint', 'parse_error', 'unknown'
  message        TEXT NOT NULL,
  -- Stack recortado (primeras ~20 líneas)
  stack          TEXT,
  -- Se resolvió solo en un reintento posterior? (actualizable)
  resolved_at    TIMESTAMPTZ,
  -- Si ya lo reportamos en un correo, guardamos aquí el id del digest_run
  -- para que no aparezca dos veces
  reported_in    BIGINT REFERENCES digest_runs(id) ON DELETE SET NULL
);

-- Query principal del correo: "fallos no resueltos en la ventana"
CREATE INDEX IF NOT EXISTS idx_ingestion_failures_pending
  ON ingestion_failures (occurred_at DESC)
  WHERE resolved_at IS NULL AND reported_in IS NULL;

-- Query de detalle por match (para cruzar con la lista de partidos fallidos)
CREATE INDEX IF NOT EXISTS idx_ingestion_failures_match
  ON ingestion_failures (match_id, occurred_at DESC)
  WHERE match_id IS NOT NULL;

-- Limpieza periódica: los fallos resueltos hace > 30 días se pueden borrar (housekeeping).
-- No lo forzamos en la migración, solo lo dejamos indicado aquí como nota.
-- DELETE FROM ingestion_failures WHERE resolved_at IS NOT NULL AND resolved_at < NOW() - INTERVAL '30 days';
